name: multiple_choice_app
description: "A Flutter application for multiple choice questions."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.0
<<<<<<< HEAD
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
=======
  audioplayers: ^5.2.1

>>>>>>> 88644d9e99fb776759be30490b5c0bb63b3f903b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
    - assets/images/
    - assets/sound/baby_music.mp3
    - assets/questions/class1.json
    - assets/questions/class2.json
    - assets/questions/class3.json
    - assets/questions/class4.json
    - assets/questions/class5.json
=======
    - assets/images/ # Đảm bảo thư mục assets được khai báo đúng
    - assets/sound/baby_music.mp3
  # An image asset can refer to one or more resolution-variant files:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the locations of the font files and their style
  # descriptors. For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
>>>>>>> 88644d9e99fb776759be30490b5c0bb63b3f903b
